edb_admin:
  admin_icon: "code" #  See https://fontawesome.com/icons/categories
  admin_title: "Admin"
  source_prefix: "media_source"
  cache_prefix: "media_cache"
  media_class: App\Entity\Media
  user_class: App\Entity\User